# Add a node to connect. Format: <ip>:<port> e.g ip:192.168.1.4
# addnode = 192.168.1.4:33333

# Bind to given address and always listen on it
# bindport = 33333

# Bind to given address and always listen on it
# bindaddress = 0.0.0.0

# Enable connection to seed node
# enable-seed-node-connection = true

# Specify data directory e.g. for linux: /home/<username>/ivoting ,  windows: <root>\Users\<username>\ivoting ,  macOS: /Users/<username>/ivoting ,  android: /data/media/<userid>/ivoting 
# default linux, macOS and android datadir:
# datadir = ./ivoting 
# default windows datadir:
# datadir = .\ivoting

# Number of threads
# par = 0

# RPC address for TCP socket
# rpc-tcp-address = 127.0.0.1

# RPC Port for TCP socket (default: 22084)
# rpc-tcp-port = 33334

# mining of block
# gen = 1
# rpcuser
# rpcpassword
